//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegistOS.Classi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIzbrannoe
    {
        public int idIzbrannogo { get; set; }
        public int idPolzovatelya { get; set; }
        public int idDocumenta { get; set; }
    
        public virtual DDocument DDocument { get; set; }
        public virtual DPolzovatel DPolzovatel { get; set; }
    }
}
