//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegistOS.Classi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIzdavOrgan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIzdavOrgan()
        {
            this.DOrganUstarNazvs = new HashSet<DOrganUstarNazv>();
            this.DDocuments = new HashSet<DDocument>();
        }
    
        public int idIzdavOrgana { get; set; }
        public string NazvanieOrgana { get; set; }
        public string OpisanieOrgana { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DOrganUstarNazv> DOrganUstarNazvs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DDocument> DDocuments { get; set; }
    }
}
