//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegistOS.Classi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DOrganUstarNazv
    {
        public int idUstarNazvOrgana { get; set; }
        public int idOrgana { get; set; }
        public string UstarNazvanie { get; set; }
        public Nullable<System.DateTime> DataIzmeneniya { get; set; }
    
        public virtual DIzdavOrgan DIzdavOrgan { get; set; }
    }
}
