//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LegistOS.Classi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DPolzovatel
    {
        public int idPolzovatelya { get; set; }
        public string Familia { get; set; }
        public string Imya { get; set; }
        public string Otchestvo { get; set; }
        public string Telefon { get; set; }
        public string Pochta { get; set; }
        public string Parol { get; set; }
        public int Rol { get; set; }
        public int Tema { get; set; }
    
        public virtual DRol DRol { get; set; }
    }
}
